server:
  http_listen_port: 9081
  grpc_listen_port: 0

positions:
  filename: /tmp/positions/positions.yaml

client:
  url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Scrape Docker container logs
  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Extract service name from container labels
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container_name
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        regex: '(.*)'
        target_label: service
      # Add job label
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        regex: '(.*)'
        target_label: job
      # Keep only useful labels
      - regex: '__meta_docker_container_label_(.+)'
        action: labelmap
        replacement: '$1'
      - regex: 'com_docker_compose_(.+)'
        action: labeldrop
      # Drop labels that are not useful
      - regex: 'container_label_(.+)'
        action: labeldrop
